# Generated by Django 3.2.7 on 2021-11-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211103_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
