# Generated by Django 3.2.7 on 2021-11-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create',
            new_name='created',
        ),
    ]
