# Generated by Django 3.2.7 on 2021-11-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_create_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post', verbose_name='Картинки'),
        ),
    ]
