# Generated by Django 3.2.7 on 2021-11-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': 'пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
